baseURL = "https://xarcanix.github.io/site"
languageCode = "en-us"
title = "xarcanix simple page"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "xarcanix simple page"

[Author]
    name = "xarcanix"

[Social]
    twitter = "xarcanix_running"
